Algoritmo "Exercicio 7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2026
Var
moedas, n, total : inteiro


Inicio

moedas <- 0
Escreval("Insira a contagem")
leia(n)

para moedas de 1 até n faca
Escreval("Contanto +1 moeda", moedas)
total <- moedas
fimpara

Escreval("")

Escreval("======================")
Escreval("Total contado: ", total)


Fimalgoritmo