Algoritmo "Calcular centímetros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2026
Var
cidade1, cidade2 : caracter
distancia : inteiro
cm : real


Inicio
Escreval("Insira o nome da primeira cidade:")
Leia(cidade1)

Escreval("Insira o nome da segunda cidade:")
Leia(cidade2)

Escreval("Qual a distância, em km, entre elas?")
Leia(distancia)

cm <- (distancia * 100000)

Escreval("A distância entre ", cidade1, " e ", cidade2, " é de: ", cm, " centímetros!")


Fimalgoritmo