Algoritmo "Registros ex1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/09/2026
Tipo TPessoa = registro
   nome  : caracter
   idade : inteiro
   altura: real
fimregistro

Var
   pessoa : TPessoa


Inicio
   Escreval("Digite o nome: ")
   leia(pessoa.nome)

   Escreval("Digite a idade: ")
   leia(pessoa.idade)

   Escreval("Digite a altura: ")
   leia(pessoa.altura)

   escreval(pessoa.nome)
   escreval(pessoa.idade)
   escreval(pessoa.altura)


Fimalgoritmo