Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2026
Var
senha : inteiro


Inicio
escreval("digite a sua senha")
leia(senha)

enquanto (senha <> 1234) faça
escreval("Senha incorreta, tente novamente")
leia(senha)
fimenquanto

escreval("Senha correta")


Fimalgoritmo