Algoritmo "Validador de Empréstimo Universitário"
// Disciplina   : Algoritmo e Lógica de Programação
// Professor   : Tiagotas
// Descrição   : Automatizar a aprovação de uma linha de crédito especial para universitários. O sistema deve analisar se o estudante cumpre os requisitos mínimos usando condições combinadas.
// Autor(a)    : Samuel
// Data atual  : 21/08/2026

Var
nome : caractere
idade : inteiro
renda_mensal : real
matricula : caractere
situacao : caractere


Inicio
Escreval("-------------------------------------------")
Escreval("-- Validador de Empréstimo Universitário --")
Escreval("-------------------------------------------")

Escreval("")

Escreval("Por gentileza, insira o seu nome:")
Leia(nome)

Escreval("")

Escreval("Agora, insira a sua idade:")
Leia(idade)

Escreval("")

Escreval("Você possui uma matrícula válida? (S/N)")
Leia(matricula)

Escreval("")

Escreval("Insira sua renda mensal:")
Leia(renda_mensal)

Escreval("")

Escreval("Por fim, você possui nome sujo? (S/N)")
Leia(situacao)

Se (idade >= 18) e (idade <= 30 então)
Escreval("Teste!")




Fimalgoritmo